name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: '27.3.4'
          elixir-version: "1.18.4"

      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted

  test_linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compile shim
        run: |
          cd priv && cargo build --release 
          cp target/release/rambo rambo-linux

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: '27.3.4'
          elixir-version: '1.18.4'

      - name: Run tests
        run: |
          mix deps.get
          mix test

